### ISSUE TITLE
reconsider box-sizing:inherit

### ISSUE THREAD

**Issue by nuxodin** [AustinGil/bedrocss#5]
Since there are cases where you explicitly want `box-sizing: content-box`, I would rather choose the following:

https://github.com/AustinGil/bedrocss/blob/0cbc6dac993e9d1ee099185f956dabaaa2da1cd2/src/base.css#L14

```css
*,
*::before,
*::after {
  box-sizing: border-box;
}
```
## Use case:
Here my `.main-width` Element should always be 40rem, regardless of its padding.
```css
.main-width {
   max-width: 40rem;
   padding-left: 2vw;
   padding-right: 2vw;
   margin: auto;
   box-sizing: content-box; 
   /* if box-sizing is inherited on every element, containing elements also has content-box */
}
```
